version: "3"
services:
  quiz-question-service:
    container_name: quiz-question-service
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 2000mb
    cpus: 2
    ports:
      - 9995:9995

  mongo:
    container_name: mongo
    image: mongo:4.4.14-rc0-focal
    mem_limit: "800mb"
    cpus: 1
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"

  redis:
    image: redis:7.0.1-alpine3.16
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379
  
