
sentinel:
  enabled: true
volumePermissions:
  enabled: true
replica:
  replicaCount: 3
  persistence:
    size: 5Gi
auth:
  enabled: true
  password: lintang
master:
  livenessProbe:
    enabled: true
  persistence:
    size: 5Gi



